import type { ShootPlan } from "./types";

const DEMO_PORTRAIT =
  "https://cdn.eazo.ai/user-contents/design-variant-subjects/4388bb97c7e8419a9a4a3537feff2e21.png";

// Sample plans that render the frontend before the real backend is wired.
export const MOCK_PLANS: ShootPlan[] = [
  {
    id: "demo-liyao",
    subjectName: "示例 · 黎瑶",
    source: "photo",
    faceShape: "鹅蛋脸偏窄",
    temperamentTags: ["清冷", "疏离感", "都市"],
    coverImageUrl: DEMO_PORTRAIT,
    createdAt: "2026-08-28T09:12:00.000Z",
    sections: [
      {
        key: "features",
        index: 1,
        title: "五官分析",
        subtitle: "Facial Analysis",
        summary: "骨相立体、中庭偏长，适合利落线条与留白构图。",
        bullets: [
          "眉眼距离适中，眼型上扬带钩，天生有镜头缘。",
          "鼻梁高挺、山根清晰，侧脸利落，适合硬光勾勒轮廓。",
          "唇形偏薄、唇峰分明，冷淡妆感更契合气质。",
        ],
        traits: [
          { label: "脸型", value: "鹅蛋脸偏窄", note: "拉长感强，避免过度修容" },
          { label: "眼型", value: "上扬丹凤", note: "眼线可平拉延伸" },
          { label: "鼻型", value: "高鼻梁窄鼻翼", note: "适合侧逆光" },
          { label: "唇形", value: "薄唇明显唇峰", note: "哑光冷调口红" },
          { label: "脸部比例", value: "中庭略长", note: "刘海或高光平衡" },
          { label: "肤色调", value: "冷白皮", note: "适配冷色系服装" },
        ],
      },
      {
        key: "makeup",
        index: 2,
        title: "妆容",
        subtitle: "Makeup",
        summary: "冷调哑光、强调眼神与轮廓，弱化甜度。",
        bullets: [
          "底妆走哑光雾面，冷调粉底提升清冷感。",
          "眼妆以灰棕平拉眼线为主，睫毛纤长不夸张。",
          "唇色选豆沙冷棕或正红，突出唇峰。",
        ],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "hair",
        index: 3,
        title: "造型 / 发型",
        subtitle: "Hair & Styling",
        summary: "利落中分或湿发背头，强化骨相与疏离感。",
        bullets: [
          "中分直发或湿发效果，露出额头与下颌线。",
          "深色发色（冷棕/黑茶）呼应冷白皮。",
          "配饰极简，金属细链或素圈耳饰。",
        ],
      },
      {
        key: "temperament",
        index: 4,
        title: "气质定位",
        subtitle: "Temperament",
        summary: "一句话人设：都市夜色里独行的清冷叙事者。",
        bullets: [
          "关键词：疏离、克制、高级、故事感。",
          "情绪基调偏冷静，眼神不迎合镜头。",
          "适合叙事型、留白型的画面表达。",
        ],
      },
      {
        key: "wardrobe",
        index: 5,
        title: "服装",
        subtitle: "Wardrobe",
        summary: "冷色极简、廓形硬朗，材质带哑光质地。",
        bullets: [
          "色系：黑、灰、藏蓝、冷白为主。",
          "廓形：西装、风衣、高领针织等硬朗单品。",
          "材质：羊毛、皮革、哑光棉，避免亮片与暖色。",
        ],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "scene",
        index: 6,
        title: "场景",
        subtitle: "Scene",
        summary: "三个推荐场景：夜色街道、极简室内、玻璃幕墙。",
        bullets: [
          "夜色街道：霓虹与湿地面反光，氛围冷冽。",
          "极简室内：水泥灰墙 + 单一自然光窗。",
          "玻璃幕墙：都市倒影，制造层次与疏离。",
        ],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "shots",
        index: 7,
        title: "分点位拍摄细节",
        subtitle: "Shot Breakdown",
        summary: "针对每个场景给出机位、景别、光线与姿势引导。",
        bullets: [],
        shots: [
          {
            scene: "夜色街道",
            camera: "平视 · 略低机位",
            framing: "半身至七分身",
            light: "侧逆霓虹光 + 反光板补面",
            angle: "3/4 侧脸",
            pose: "缓步回眸，视线越过镜头",
            composition: "人物置于右三分线，留出街景纵深",
          },
          {
            scene: "极简室内",
            camera: "平视 · 齐眼高",
            framing: "近景特写",
            light: "单一窗光柔光",
            angle: "正面微侧",
            pose: "手轻托下颌，眼神向下",
            composition: "大面积留白，人物偏左",
          },
          {
            scene: "玻璃幕墙",
            camera: "俯拍 · 高机位",
            framing: "全身",
            light: "自然天光 + 玻璃反射",
            angle: "背身回头",
            pose: "倚墙远眺，制造倒影",
            composition: "利用倒影做对称层次",
          },
        ],
      },
      {
        key: "photographer",
        index: 8,
        title: "摄影师风格案例",
        subtitle: "Photographer Styles",
        summary: "匹配三种清冷叙事的摄影风格参照。",
        bullets: [],
        cases: [
          {
            style: "冷调都市纪实",
            vibe: "低饱和、硬光、街头叙事",
            reference: "多用侧逆光与环境反光，人物不直视镜头",
          },
          {
            style: "极简室内肖像",
            vibe: "单一光源、大留白、克制构图",
            reference: "窗光柔面、近景特写，突出神态与皮肤质感",
          },
          {
            style: "玻璃倒影时装",
            vibe: "都市反射、层次叠加、冷色调",
            reference: "利用玻璃/水面倒影构建对称与疏离感",
          },
        ],
      },
    ],
  },
  {
    id: "demo-anke",
    subjectName: "示例 · 安可",
    source: "text",
    faceShape: "圆润偏软",
    temperamentTags: ["元气", "邻家", "暖阳"],
    coverImageUrl: DEMO_PORTRAIT,
    createdAt: "2026-08-25T14:40:00.000Z",
    sections: [
      {
        key: "features",
        index: 1,
        title: "五官分析",
        subtitle: "Facial Analysis",
        summary: "面部圆润、亲和力强，适合暖调柔光与生活化场景。",
        bullets: [
          "苹果肌饱满，笑容有感染力，天生上镜。",
          "圆眼大而亮，适合放大眼神的甜系妆容。",
          "唇形圆润，暖色系口红更显气色。",
        ],
        traits: [
          { label: "脸型", value: "圆润偏软", note: "适度修容拉长" },
          { label: "眼型", value: "圆眼", note: "卧蚕高光提亮" },
          { label: "鼻型", value: "小巧鼻头", note: "自然鼻影即可" },
          { label: "唇形", value: "圆润饱满", note: "水润暖调" },
          { label: "脸部比例", value: "三庭均衡", note: "刘海可选" },
          { label: "肤色调", value: "暖黄皮", note: "适配暖色系" },
        ],
      },
      {
        key: "makeup",
        index: 2,
        title: "妆容",
        subtitle: "Makeup",
        summary: "暖调水光、放大眼神，营造元气甜感。",
        bullets: ["水光底妆提气色", "橘棕眼影 + 卧蚕高光", "珊瑚橘或蜜桃色唇釉"],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "hair",
        index: 3,
        title: "造型 / 发型",
        subtitle: "Hair & Styling",
        summary: "空气刘海 + 微卷长发，强化亲和邻家感。",
        bullets: ["空气感刘海柔化脸型", "暖棕发色呼应暖黄皮", "配饰选发夹、丝带等甜系元素"],
      },
      {
        key: "temperament",
        index: 4,
        title: "气质定位",
        subtitle: "Temperament",
        summary: "一句话人设：午后阳光里爱笑的邻家女孩。",
        bullets: ["关键词：元气、温暖、亲和、治愈", "情绪明亮、乐于与镜头互动", "适合生活流、暖调叙事"],
      },
      {
        key: "wardrobe",
        index: 5,
        title: "服装",
        subtitle: "Wardrobe",
        summary: "暖色柔软、日常廓形，材质舒适透气。",
        bullets: ["色系：米白、奶橘、浅黄、草绿", "廓形：针织、连衣裙、衬衫等日常单品", "材质：棉麻、针织，柔软自然"],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "scene",
        index: 6,
        title: "场景",
        subtitle: "Scene",
        summary: "三个推荐场景：暖阳咖啡馆、公园草地、家居窗边。",
        bullets: ["暖阳咖啡馆：木质暖光，生活气息", "公园草地：自然光 + 绿意背景", "家居窗边：柔光 + 温馨氛围"],
        imageUrl: DEMO_PORTRAIT,
      },
      {
        key: "shots",
        index: 7,
        title: "分点位拍摄细节",
        subtitle: "Shot Breakdown",
        summary: "针对每个场景给出机位、景别、光线与姿势引导。",
        bullets: [],
        shots: [
          {
            scene: "暖阳咖啡馆",
            camera: "平视 · 齐眼高",
            framing: "半身",
            light: "窗边暖光顺光",
            angle: "正面微笑",
            pose: "手捧咖啡杯，侧头轻笑",
            composition: "前景虚化杯具，暖色氛围",
          },
          {
            scene: "公园草地",
            camera: "略低机位仰拍",
            framing: "全身",
            light: "午后自然光",
            angle: "正面走动",
            pose: "自然行走、回头笑",
            composition: "低机位收入绿意与天空",
          },
          {
            scene: "家居窗边",
            camera: "平视",
            framing: "近景",
            light: "柔和窗光",
            angle: "3/4 侧脸",
            pose: "倚窗托腮，眼神看向窗外",
            composition: "窗框做前景，留白右侧",
          },
        ],
      },
      {
        key: "photographer",
        index: 8,
        title: "摄影师风格案例",
        subtitle: "Photographer Styles",
        summary: "匹配三种暖调生活的摄影风格参照。",
        bullets: [],
        cases: [
          {
            style: "暖调生活纪实",
            vibe: "暖光、柔焦、自然抓拍",
            reference: "顺光暖调，捕捉真实笑容与互动",
          },
          {
            style: "日系清新写真",
            vibe: "高亮度、低对比、通透",
            reference: "自然光柔面，浅景深突出人物",
          },
          {
            style: "家居温馨肖像",
            vibe: "窗光、温暖色温、生活场景",
            reference: "窗边柔光近景，营造治愈氛围",
          },
        ],
      },
    ],
  },
];

export function getMockPlan(id: string): ShootPlan | undefined {
  return MOCK_PLANS.find((p) => p.id === id);
}
